apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indic-ai-data-loader.fullname" . }}
  labels:
    app: {{ include "indic-ai-data-loader.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "indic-ai-data-loader.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "indic-ai-data-loader.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "local"
          volumeMounts:
            - name: raw-data
              mountPath: /data/raw
            - name: metadata-image
              mountPath: /data/metadata/image
            - name: features-image
              mountPath: /data/features/image
      volumes:
        - name: raw-data
          hostPath:
            path: /data/raw
            type: Directory
        - name: metadata-image
          hostPath:
            path: /data/metadata/image
            type: Directory
        - name: features-image
          hostPath:
            path: /data/features/image
            type: DirectoryOrCreate